### ISSUE TITLE
作業系統windows server 2016能安裝嗎？

### ISSUE THREAD

**Issue by Leo900805** [iineva/ipa-server#25]
你好，請問ipa-server 這個專案能安裝在windows server 2016嗎？

**Comment by iineva** [comment]
理论上能安装docker或者NodeJS都可以运行

**Comment by Leo900805** [comment]
在安裝過程得到這個錯誤訊息：ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
版本太舊了？如何更新呢？

**Comment by iineva** [comment]
你用什么形式安装的？
安装什么的过程中提示的？提供一下完整日志

**Comment by Leo900805** [comment]
我是參考這個文件 https://docs.docker.com/compose/install/ 安裝的，之後改用nodejs 之後測試又顯示以下錯誤：
Upload fail: TypeError: Cannot read property 'path' of undefined
    at Object.add (C:\Users\Administrator\ipa-server\libs\ipa-manager.js:124:63)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\ipa-server\index.js:48:5
    at async Object.<anonymous> (C:\Users\Administrator\ipa-server\middle\upload.js:43:5)
    at async serve (C:\Users\Administrator\ipa-server\node_modules\koa-static\index.js:59:5)
    at async serve (C:\Users\Administrator\ipa-server\node_modules\koa-static\index.js:59:5)
    at async C:\Users\Administrator\ipa-server\index.js:19:3
TypeError: Cannot read property 'path' of undefined
    at Object.add (C:\Users\Administrator\ipa-server\libs\ipa-manager.js:124:63)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\ipa-server\index.js:48:5
    at async Object.<anonymous> (C:\Users\Administrator\ipa-server\middle\upload.js:43:5)
    at async serve (C:\Users\Administrator\ipa-server\node_modules\koa-static\index.js:59:5)
    at async serve (C:\Users\Administrator\ipa-server\node_modules\koa-static\index.js:59:5)
    at async C:\Users\Administrator\ipa-server\index.js:19:3

**Comment by Leo900805** [comment]
nodejs的domain name 是不是需要有https才能上傳呢·？

**Comment by iineva** [comment]
上传不需要https，只有在iOS设备下载安装的时候才需要https
