### ISSUE TITLE
每次下载文件的时候出错

### ISSUE THREAD

**Issue by bbbccc-hello** [iineva/ipa-server#9]
*** SERVER ERROR ***
 { Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:848:14)
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  headerSent: true }
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn say ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
请问，问题出在哪？

**Comment by iineva** [comment]
只靠这些信息不能排查，推荐用docker来部署，可以规避很多问题
